// <auto-generated />
namespace Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CompanyPhone1 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Company", "UserProfile_UserId", "dbo.UserProfile");
            DropIndex("dbo.Company", new[] { "UserProfile_UserId" });
            RenameColumn(table: "dbo.Company", name: "UserProfile_UserId", newName: "UserId");
            AddForeignKey("dbo.Company", "UserId", "dbo.UserProfile", "UserId", cascadeDelete: true);
            CreateIndex("dbo.Company", "UserId");
        }
        
        public override void Down()
        {
            DropIndex("dbo.Company", new[] { "UserId" });
            DropForeignKey("dbo.Company", "UserId", "dbo.UserProfile");
            RenameColumn(table: "dbo.Company", name: "UserId", newName: "UserProfile_UserId");
            CreateIndex("dbo.Company", "UserProfile_UserId");
            AddForeignKey("dbo.Company", "UserProfile_UserId", "dbo.UserProfile", "UserId");
        }
    }
}
