// <auto-generated />
namespace Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Initial2 : DbMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.Opportunity", "OpportunityDate", c => c.String());
        }
        
        public override void Down()
        {
            AlterColumn("dbo.Opportunity", "OpportunityDate", c => c.DateTime(nullable: false));
        }
    }
}
