// <auto-generated />
namespace Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CompUserFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompUserFK));
        
        string IMigrationMetadata.Id
        {
            get { return "201303191502268_CompUserFK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
