// <auto-generated />
namespace Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Initial : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Company",
                c => new
                    {
                        CompanyId = c.Int(nullable: false, identity: true),
                        CompanyApproved = c.Boolean(nullable: false),
                        CompanyName = c.String(maxLength: 50),
                        CharityNumber = c.String(maxLength: 10),
                        CompanyContactName = c.String(maxLength: 50),
                        CompanyContactEmail = c.String(maxLength: 100),
                        CompanyDetails = c.String(maxLength: 200),
                        CompanyAddress = c.String(maxLength: 200),
                        CompanyPostcode = c.String(maxLength: 8),
                        UserProfile_UserId = c.Int(),
                    })
                .PrimaryKey(t => t.CompanyId)
                .ForeignKey("dbo.UserProfile", t => t.UserProfile_UserId)
                .Index(t => t.UserProfile_UserId);
            
            CreateTable(
                "dbo.UserProfile",
                c => new
                    {
                        UserId = c.Int(nullable: false, identity: true),
                        UserName = c.String(),
                    })
                .PrimaryKey(t => t.UserId);
            
            CreateTable(
                "dbo.OpportunityStatus",
                c => new
                    {
                        OpportunityStatusId = c.Int(nullable: false, identity: true),
                        OpportunityStatusDescription = c.String(maxLength: 200),
                    })
                .PrimaryKey(t => t.OpportunityStatusId);
            
            CreateTable(
                "dbo.Opportunity",
                c => new
                    {
                        CompanyId = c.Int(nullable: false),
                        OpportunityId = c.Int(nullable: false, identity: true),
                        OpportunityTitle = c.String(maxLength: 50),
                        OpportunityDescription = c.String(nullable: false, maxLength: 200),
                        MinNumberofVolunteers = c.Int(nullable: false),
                        MaxNumberofVolunteers = c.Int(nullable: false),
                        OpportunityDate = c.DateTime(nullable: false),
                        OpportunityStatusId = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.OpportunityId)
                .ForeignKey("dbo.OpportunityStatus", t => t.OpportunityStatusId, cascadeDelete: true)
                .ForeignKey("dbo.Company", t => t.CompanyId, cascadeDelete: true)
                .Index(t => t.OpportunityStatusId)
                .Index(t => t.CompanyId);
            
            CreateTable(
                "dbo.OpportunityEmployeeMap",
                c => new
                    {
                        OpportunityId = c.Int(nullable: false),
                        OpportunityEmployeeMapId = c.Int(nullable: false, identity: true),
                        EmployeeId = c.Int(nullable: false),
                        EmployeeRoleId = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.OpportunityEmployeeMapId)
                .ForeignKey("dbo.Opportunity", t => t.OpportunityId, cascadeDelete: true)
                .ForeignKey("dbo.Employee", t => t.EmployeeId, cascadeDelete: true)
                .ForeignKey("dbo.EmployeeRole", t => t.EmployeeRoleId, cascadeDelete: true)
                .Index(t => t.OpportunityId)
                .Index(t => t.EmployeeId)
                .Index(t => t.EmployeeRoleId);
            
            CreateTable(
                "dbo.Employee",
                c => new
                    {
                        EmployeeId = c.Int(nullable: false, identity: true),
                        NTLogin = c.String(),
                        EmployeeName = c.String(),
                        EmployeeEmail = c.String(),
                        EmployeeDepartment = c.String(),
                        EmployeeContactNumber = c.String(),
                        EmployeeWorkPostcode = c.String(),
                    })
                .PrimaryKey(t => t.EmployeeId);
            
            CreateTable(
                "dbo.EmployeeRole",
                c => new
                    {
                        OpportunityRoleId = c.Int(nullable: false, identity: true),
                        OpportunityRoleDescription = c.String(maxLength: 200),
                    })
                .PrimaryKey(t => t.OpportunityRoleId);
            
        }
        
        public override void Down()
        {
            DropIndex("dbo.OpportunityEmployeeMap", new[] { "EmployeeRoleId" });
            DropIndex("dbo.OpportunityEmployeeMap", new[] { "EmployeeId" });
            DropIndex("dbo.OpportunityEmployeeMap", new[] { "OpportunityId" });
            DropIndex("dbo.Opportunity", new[] { "CompanyId" });
            DropIndex("dbo.Opportunity", new[] { "OpportunityStatusId" });
            DropIndex("dbo.Company", new[] { "UserProfile_UserId" });
            DropForeignKey("dbo.OpportunityEmployeeMap", "EmployeeRoleId", "dbo.EmployeeRole");
            DropForeignKey("dbo.OpportunityEmployeeMap", "EmployeeId", "dbo.Employee");
            DropForeignKey("dbo.OpportunityEmployeeMap", "OpportunityId", "dbo.Opportunity");
            DropForeignKey("dbo.Opportunity", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Opportunity", "OpportunityStatusId", "dbo.OpportunityStatus");
            DropForeignKey("dbo.Company", "UserProfile_UserId", "dbo.UserProfile");
            DropTable("dbo.EmployeeRole");
            DropTable("dbo.Employee");
            DropTable("dbo.OpportunityEmployeeMap");
            DropTable("dbo.Opportunity");
            DropTable("dbo.OpportunityStatus");
            DropTable("dbo.UserProfile");
            DropTable("dbo.Company");
        }
    }
}
