// <auto-generated />
namespace Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Initial3 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Opportunity", "OpportunityAdditionalInformation", c => c.String(maxLength: 1000));
            AddColumn("dbo.Opportunity", "OpportunityLocationName", c => c.String());
            AddColumn("dbo.Opportunity", "OpportunityPostcode", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.Opportunity", "OpportunityPostcode");
            DropColumn("dbo.Opportunity", "OpportunityLocationName");
            DropColumn("dbo.Opportunity", "OpportunityAdditionalInformation");
        }
    }
}
